"""init db

Revision ID: 1125f207ccec
Revises: d9334afd8a12
Create Date: 2025-10-07 22:56:46.038253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1125f207ccec'
down_revision: Union[str, Sequence[str], None] = 'd9334afd8a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('arabic', sa.Text(), nullable=False),
    sa.Column('transliteration', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('audio_map', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duas_id'), 'duas', ['id'], unique=False)
    op.create_index(op.f('ix_duas_title'), 'duas', ['title'], unique=False)
    op.create_table('hadiths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection', sa.String(length=100), nullable=False),
    sa.Column('hadith_number', sa.Integer(), nullable=False),
    sa.Column('arabic_text', sa.Text(), nullable=True),
    sa.Column('english_text', sa.Text(), nullable=True),
    sa.Column('narrator', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hadiths_collection'), 'hadiths', ['collection'], unique=False)
    op.create_index(op.f('ix_hadiths_hadith_number'), 'hadiths', ['hadith_number'], unique=False)
    op.create_index(op.f('ix_hadiths_id'), 'hadiths', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hadiths_id'), table_name='hadiths')
    op.drop_index(op.f('ix_hadiths_hadith_number'), table_name='hadiths')
    op.drop_index(op.f('ix_hadiths_collection'), table_name='hadiths')
    op.drop_table('hadiths')
    op.drop_index(op.f('ix_duas_title'), table_name='duas')
    op.drop_index(op.f('ix_duas_id'), table_name='duas')
    op.drop_table('duas')
    # ### end Alembic commands ###
