"""Add notes, benefits, source, category to Dua

Revision ID: 2edb6ec9fef5
Revises: 1125f207ccec
Create Date: 2025-10-11 04:30:01.508383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2edb6ec9fef5'
down_revision: Union[str, Sequence[str], None] = '1125f207ccec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('duas', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('duas', sa.Column('benefits', sa.Text(), nullable=True))
    op.add_column('duas', sa.Column('source', sa.Text(), nullable=True))
    op.add_column(
        'duas',
        sa.Column('category', sa.String(length=100), nullable=False, server_default='General')
    )

    op.add_column('hadiths', sa.Column('book', sa.String(), nullable=True))
    op.add_column('hadiths', sa.Column('arabic', sa.Text(), nullable=True))
    op.add_column('hadiths', sa.Column('english', sa.Text(), nullable=True))
    op.add_column('hadiths', sa.Column('category', sa.String(), nullable=True))
    op.alter_column('hadiths', 'hadith_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_hadiths_collection'), table_name='hadiths')
    op.drop_index(op.f('ix_hadiths_hadith_number'), table_name='hadiths')
    op.drop_column('hadiths', 'arabic_text')
    op.drop_column('hadiths', 'collection')
    op.drop_column('hadiths', 'english_text')

    # Remove the default after applying so new rows won't auto get 'General'
    op.alter_column('duas', 'category', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hadiths', sa.Column('english_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('hadiths', sa.Column('collection', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('hadiths', sa.Column('arabic_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_hadiths_hadith_number'), 'hadiths', ['hadith_number'], unique=False)
    op.create_index(op.f('ix_hadiths_collection'), 'hadiths', ['collection'], unique=False)
    op.alter_column('hadiths', 'hadith_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('hadiths', 'category')
    op.drop_column('hadiths', 'english')
    op.drop_column('hadiths', 'arabic')
    op.drop_column('hadiths', 'book')
    op.drop_column('duas', 'category')
    op.drop_column('duas', 'source')
    op.drop_column('duas', 'benefits')
    op.drop_column('duas', 'notes')
    # ### end Alembic commands ###
