"""initial migration

Revision ID: 69d3bfe217ba
Revises: 
Create Date: 2025-11-11 01:31:22.543247
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69d3bfe217ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - safely edited ###
    # Commenting out drops to preserve existing data
    # op.drop_table('admin_users')
    # op.drop_table('conversations')
    # op.drop_table('messages')
    # op.drop_table('admin_notes')
    # op.drop_index(op.f('ix_zakat_records_id'), table_name='zakat_records')
    # op.drop_index(op.f('ix_zakat_records_user_id'), table_name='zakat_records')
    # op.drop_table('zakat_records')
    # op.drop_table('files')
    # op.drop_table('ratings')
    # op.drop_index(op.f('ix_contact_messages_id'), table_name='contact_messages')
    # op.drop_table('contact_messages')
    # op.drop_index(op.f('ix_categories_id'), table_name='dua_categories')

    # Keep only safe operations
    op.create_index(op.f('ix_dua_categories_id'), 'dua_categories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - safely edited ###
    op.drop_index(op.f('ix_dua_categories_id'), table_name='dua_categories')
    op.create_index(op.f('ix_categories_id'), 'dua_categories', ['id'], unique=False)
    # Do NOT drop any tables to preserve data
    # ### end Alembic commands ###
