"""update hadith model

Revision ID: 97c140675287
Revises: 2edb6ec9fef5
Create Date: 2025-10-15 02:37:32.073310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c140675287'
down_revision: Union[str, Sequence[str], None] = '2edb6ec9fef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hadiths', sa.Column('id_in_book', sa.Integer(), nullable=True))
    op.add_column('hadiths', sa.Column('chapter_id', sa.Integer(), nullable=True))
    op.add_column('hadiths', sa.Column('book_id', sa.Integer(), nullable=True))
    op.add_column('hadiths', sa.Column('source', sa.String(), nullable=True))
    op.alter_column('hadiths', 'arabic',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column(
    'hadiths',
    'english',
    existing_type=sa.TEXT(),
    type_=sa.JSON(),
    nullable=False,
    postgresql_using='english::json'
)

    op.drop_column('hadiths', 'hadith_number')
    op.drop_column('hadiths', 'narrator')
    op.drop_column('hadiths', 'book')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hadiths', sa.Column('book', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hadiths', sa.Column('narrator', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('hadiths', sa.Column('hadith_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('hadiths', 'english',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('hadiths', 'arabic',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('hadiths', 'source')
    op.drop_column('hadiths', 'book_id')
    op.drop_column('hadiths', 'chapter_id')
    op.drop_column('hadiths', 'id_in_book')
    # ### end Alembic commands ###
