"""create contact_messages table

Revision ID: ba11805b145d
Revises: e73ea1cb7faa
Create Date: 2025-10-27 22:54:08.043859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba11805b145d'
down_revision: Union[str, Sequence[str], None] = 'e73ea1cb7faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_id'), 'contact_messages', ['id'], unique=False)
    op.drop_index(op.f('ix_tasbih_history_id'), table_name='tasbih_history')
    op.drop_table('tasbih_history')
    op.drop_index(op.f('ix_tasbih_counters_id'), table_name='tasbih_counters')
    op.drop_index(op.f('ix_tasbih_counters_user_id'), table_name='tasbih_counters')
    op.drop_table('tasbih_counters')
    op.drop_index(op.f('ix_dhikr_counts_id'), table_name='dhikr_counts')
    op.drop_index(op.f('ix_dhikr_counts_user_id'), table_name='dhikr_counts')
    op.drop_table('dhikr_counts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dhikr_counts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_reset', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('dhikr_counts_pkey'))
    )
    op.create_index(op.f('ix_dhikr_counts_user_id'), 'dhikr_counts', ['user_id'], unique=False)
    op.create_index(op.f('ix_dhikr_counts_id'), 'dhikr_counts', ['id'], unique=False)
    op.create_table('tasbih_counters',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tasbih_counters_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tasbih_counters_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_tasbih_counters_user_id'), 'tasbih_counters', ['user_id'], unique=False)
    op.create_index(op.f('ix_tasbih_counters_id'), 'tasbih_counters', ['id'], unique=False)
    op.create_table('tasbih_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('counter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['counter_id'], ['tasbih_counters.id'], name=op.f('tasbih_history_counter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tasbih_history_pkey'))
    )
    op.create_index(op.f('ix_tasbih_history_id'), 'tasbih_history', ['id'], unique=False)
    op.drop_index(op.f('ix_contact_messages_id'), table_name='contact_messages')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
