"""create tasbih tables

Revision ID: f82e3d91c545
Revises: 97c140675287
Create Date: 2025-10-16 08:34:55.331350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f82e3d91c545'
down_revision: Union[str, Sequence[str], None] = '97c140675287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasbih_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('target', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasbih_counters_id'), 'tasbih_counters', ['id'], unique=False)
    op.create_index(op.f('ix_tasbih_counters_user_id'), 'tasbih_counters', ['user_id'], unique=False)
    op.create_table('zakat_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('assets_total', sa.Float(), nullable=False),
    sa.Column('savings', sa.Float(), nullable=False),
    sa.Column('gold_price_per_gram', sa.Float(), nullable=True),
    sa.Column('nisab', sa.Float(), nullable=True),
    sa.Column('zakat_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zakat_records_id'), 'zakat_records', ['id'], unique=False)
    op.create_index(op.f('ix_zakat_records_user_id'), 'zakat_records', ['user_id'], unique=False)
    op.create_table('tasbih_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('counter_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['counter_id'], ['tasbih_counters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasbih_history_id'), 'tasbih_history', ['id'], unique=False)
    op.drop_index(op.f('ix_lectures_id'), table_name='lectures')
    op.drop_table('lectures')
    op.drop_index(op.f('ix_quran_verses_id'), table_name='quran_verses')
    op.drop_table('quran_verses')
    op.drop_column('hadiths', 'narrator')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hadiths', sa.Column('narrator', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('quran_verses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('surah', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ayah', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('arabic', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('translation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('audio_map', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('quran_verses_pkey'))
    )
    op.create_index(op.f('ix_quran_verses_id'), 'quran_verses', ['id'], unique=False)
    op.create_table('lectures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('speaker', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('lectures_pkey'))
    )
    op.create_index(op.f('ix_lectures_id'), 'lectures', ['id'], unique=False)
    op.drop_index(op.f('ix_tasbih_history_id'), table_name='tasbih_history')
    op.drop_table('tasbih_history')
    op.drop_index(op.f('ix_zakat_records_user_id'), table_name='zakat_records')
    op.drop_index(op.f('ix_zakat_records_id'), table_name='zakat_records')
    op.drop_table('zakat_records')
    op.drop_index(op.f('ix_tasbih_counters_user_id'), table_name='tasbih_counters')
    op.drop_index(op.f('ix_tasbih_counters_id'), table_name='tasbih_counters')
    op.drop_table('tasbih_counters')
    # ### end Alembic commands ###
